load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "LibraryC",
    module_name = "LibraryC",
    srcs = glob(["**/**/*.swift"]),
    visibility = ["//visibility:public"],
)